server:
  port: 8082
spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: users-service
          uri: lb://user-mngmnt
          predicates:
            - Path=/users/**,/login/**
          filters:
            - AuthenticationFilter
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: task-maintenance-service
          uri: lb://maintenance-tasks
          predicates:
            - Path=/notification/**,/task/**,/team/**,/user/**
          filters:
            - AuthenticationFilter
#            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#        - id: react-native
#          uri: http://localhost:8081/
#          predicates:
#             - Path=/**
#        - id: react
#          uri: http://localhost:3000/
#          predicates:
#            - Path=/**




eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
    enabled: true
    fetch-registry: true
    should-enforce-registration-at-init: true

jwt:
  secretKey: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437