server:
  port: 8082
spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: lb://user-mngmnt
          predicates:
            - Path=/users/**,/login/**
          filters:
            - AuthenticationFilter



eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
    enabled: true
    fetch-registry: true
    should-enforce-registration-at-init: true


jwt:
  secretKey: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437